### ISSUE TITLE
Id love to use this with react but your example doesn't work

### ISSUE THREAD

**Issue by utb2017** [vkrbt/pinch-to-zoom#1]
TypeError: this.pinchToZoom.unsubscribe is not a function

Is the error. Your spelling is wrong on subscribe and that example component is not a component, its missing a constructor and do we need to import pinch zoom? This is pretty confusing, I cant lie.

**Comment by lasseborly** [comment]
When https://github.com/vkrbt/pinch-to-zoom/pull/2 is merged it should be fixed @utb2017
